name: Delete Old Docker Image

on:
  workflow_dispatch:  

jobs:

  cleanup-pg:
    runs-on: ubuntu-latest

    steps:

      - name: Cleanup Docker images from GHCR
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          owner: multi-repo
          repository: postgres
          keep-n-tagged: 1
          package: postgres/pg
          dry-run: false
