name: Delete Old Docker Image

on:
  workflow_dispatch:  

jobs:

  cleanup-pg:
    runs-on: ubuntu-latest
    steps:

      - name: Cleanup Docker images from GHCR
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          owner: ${{ github.repository_owner }}
          repository: multi-repo/Postgres
          keep-n-tagged: 1
          package: multi-repo/Postgres/pg
          dry-run: false
