name: Build Docker Images

on:
  push:
      branches:
        - main  
        
jobs:


  trigger-build:
    uses: multi-repo/workflows/.github/workflows/kaniko-build.yml@main
    with:
      image-name: ${{ github.repository }}/pg
    secrets:
      personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}



  trigger-cleanup:
      uses: multi-repo/workflows/.github/workflows/clean-registry.yml@main
      with:
        owner: multi-repo
        repository: postgres
        package: postgres/pg
        keep_n_tagged: 2
        dry_run: true  
      secrets:
        personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


  deploy:
    needs: [trigger-cleanup, trigger-build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to environment
        run: |
          echo "Deploying application"
